### ISSUE TITLE
show-ref not expected to be empty

### ISSUE THREAD

**Issue by tucked** [dmtucker/git-rebase-branches#1]
```
$ git stash push
No local changes to save
Traceback (most recent call last):
  File "/ifs/home/dtucker/.local/bin/git-rebase-branches", line 8, in <module>
    sys.exit(main())
  File "/ifs/home/dtucker/.local/pipx/venvs/git-rebase-branches/lib/python3.8/site-packages/git_rebase_branches.py", line 106, in main
    result = subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'show-ref', '--hash', 'HEAD']' returned non-zero exit status 1.
```

**Comment by tucked** [comment]
Might need to pass `--head` to that command
https://github.com/dmtucker/git-rebase-branches/blob/b7f09d95339299e3a43544b127eb769ae32deddf/src/git_rebase_branches.py#L107
```
    --head                show the HEAD reference, even if it would be filtered out
```
``` console
$ git show-ref --hash HEAD
$ git show-ref --head --hash HEAD
1341850444a9c3902ad69a6e388d62d893d6c1de
```
