### ISSUE TITLE
CalledProcessError on branch named "stash"

### ISSUE THREAD

**Issue by dmtucker** [dmtucker/git-rebase-branches#3]
```
$ git switch heads/stash
fatal: a branch is expected, got 'refs/heads/stash'
Traceback (most recent call last):
  File "/home/dtux/.local/bin/git-rebase-branches", line 8, in <module>
    sys.exit(main())
  File "/home/dtux/.local/pipx/venvs/git-rebase-branches/lib/python3.10/site-packages/git_rebase_branches.py", line 152, in main
    run(["git", "switch", branch], check=True)
  File "/home/dtux/.local/pipx/venvs/git-rebase-branches/lib/python3.10/site-packages/git_rebase_branches.py", line 183, in run
    return subprocess.run(command, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'switch', 'heads/stash']' returned non-zero exit status 128.
```

**Comment by dmtucker** [comment]
I can't reproduce this... It seems like an issue with referring to the branch named "stash" as `heads/stash` (not because of the name -- the `git stash` is `refs/stash`):
```console
$ git branch -vv
* master a643e9d Tue Aug 12 04:11:33 PM PDT 2025
  stash  c150c38 Initial commit
$ ll .git/refs/heads/stash 
-rw-rw-r-- 1 dtux dtux 41 Aug 12 16:12 .git/refs/heads/stash
$ git switch heads/stash
fatal: a branch is expected, got 'refs/heads/stash'
```

**Comment by dmtucker** [comment]
Here's a repro:
```sh
git init
git commit --no-gpg-sign --allow-empty -m "Initial commit"
git branch stash
git commit --no-gpg-sign --allow-empty -m "$(date)"
```
- If we try to repro here, it doesn't work:
  ```console
  $ git-rebase-branches master
  $ git stash push
  No local changes to save
  $ git log -n1
  a643e9d (HEAD -> master) Tue Aug 12 04:11:33 PM PDT 2025
  $ git -c advice.detachedHead=false checkout master
  Already on 'master'
  $ git branch --no-contains HEAD '--format=%(refname:short)'
  stash
  $ git switch stash
  Switched to branch 'stash'
  $ git rebase master
  Successfully rebased and updated refs/heads/stash.
  $ git -c advice.detachedHead=false checkout master
  Switched to branch 'master'
  
  ==================================== SUMMARY ====================================
  - stash (succeeded)
  ```
  - Specifically, note the `--no-contains` command:
    ``` console
    $ git branch --no-contains HEAD '--format=%(refname:short)'
    stash
    ```

To complete the repro, we need to _also_ `stash` something:
```sh
touch foo
git add foo
git stash
```
_Now_ if we try to repro:
```console
$ git-rebase-branches master
$ git stash push
No local changes to save
$ git log -n1
a643e9d (HEAD -> master) Tue Aug 12 04:11:33 PM PDT 2025
$ git -c advice.detachedHead=false checkout master
Already on 'master'
$ git branch --no-contains HEAD '--format=%(refname:short)'
heads/stash
$ git switch heads/stash
fatal: a branch is expected, got 'refs/heads/stash'
Traceback (most recent call last):
  File "/home/dtux/.local/bin/git-rebase-branches", line 8, in <module>
    sys.exit(main())
  File "/home/dtux/.local/pipx/venvs/git-rebase-branches/lib/python3.10/site-packages/git_rebase_branches.py", line 152, in main
    run(["git", "switch", branch], check=True)
  File "/home/dtux/.local/pipx/venvs/git-rebase-branches/lib/python3.10/site-packages/git_rebase_branches.py", line 183, in run
    return subprocess.run(command, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['git', 'switch', 'heads/stash']' returned non-zero exit status 128.
```
- Note how the `--no-contains` command changed:
  ```console
  git branch --no-contains HEAD '--format=%(refname:short)'
  heads/stash
  ```

This does NOT repro in v2.0.0:
```console
$ git-rebase-branches master
$ git branch --no-contains master '--format=%(refname:short)'
heads/stash
$ git stash push --include-untracked
No local changes to save
$ git log -n1
a643e9d (HEAD -> master) Tue Aug 12 04:11:33 PM PDT 2025
$ git rebase master heads/stash
Successfully rebased and updated detached HEAD.
$ git -c advice.detachedHead=false checkout master
Switched to branch 'master'

==================================== SUMMARY ====================================
- heads/stash (succeeded)
```
It was (inadvertently) fixed by https://github.com/dmtucker/git-rebase-branches/commit/2c33f5a29bdd57424536925f4e36f2a8a60bc5f8
